In [2]:
import pandas as pd
import torch

In [3]:
data=pd.read_csv("house_tiny.csv")

In [4]:
data

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [6]:
inputs=data.iloc[:,0:2]

In [7]:
target=data.iloc[:,2]

In [8]:
inputs=pd.get_dummies(inputs,dummy_na=True)

In [11]:
inputs=inputs.fillna(inputs.mean())

In [13]:
inputs

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True

In [14]:
x=torch.tensor(inputs.to_numpy(dtype=float))

In [15]:
y=torch.tensor(target.to_numpy(dtype=float))

In [16]:
x

tensor([[3., 0., 1.],
        [2., 0., 1.],
        [4., 1., 0.],
        [3., 0., 1.]], dtype=torch.float64)

In [17]:
y

tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)